name: Obsoleted parameters

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:

jobs:
  add_extras_bucket:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - if: ${{ github.event_name == 'pull_request' }}
        name: Run actions locally
        uses: ./
        with:
          buckets: extras
        continue-on-error: true

      - if: >
          ${{ github.event_name == 'push'
          || github.event_name == 'workflow_dispatch' }}
        uses: winpax/scoop-setup@main
        with:
          buckets: extras
        continue-on-error: true

      - if: ${{ github.event_name == 'schedule' }}
        uses: winpax/scoop-setup@v1.0.0
        with:
          buckets: extras
        continue-on-error: true

      - name: Validate extras bucket is not available
        shell: pwsh
        run: |
          if([bool](scoop bucket list | Select-String -Quiet "extras")) {
            Write-Error "Unexepected extras bucket found." -ErrorAction Stop
          }

  add_nonportable_bucket:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - if: ${{ github.event_name == 'pull_request' }}
        name: Run actions locally
        uses: ./
        with:
          buckets: nonportable
        continue-on-error: true

      - if: >
          ${{ github.event_name == 'push'
          || github.event_name == 'workflow_dispatch' }}
        uses: winpax/scoop-setup@main
        with:
          buckets: nonportable
        continue-on-error: true

      - if: ${{ github.event_name == 'schedule' }}
        uses: winpax/scoop-setup@v1.0.0
        with:
          buckets: nonportable
        continue-on-error: true

      - name: Validate nonportable bucket is not available
        shell: pwsh
        run: |
          if([bool](scoop bucket list | Select-String -Quiet "nonportable")) {
            Write-Error "Unexpected nonportable bucket found." -ErrorAction Stop
          }
