name: run_as_admin

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:

jobs:
  GitHub_default_runner_without_RunAsAdmin:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - if: ${{ github.event_name == 'pull_request' }}
        name: Run actions locally
        uses: ./
        with:
          admin: false
        continue-on-error: true

      - if: >
          ${{ github.event_name == 'push'
          || github.event_name == 'workflow_dispatch' }}
        uses: winpax/scoop-setup@main
        with:
          admin: false
        continue-on-error: true

      - if: ${{ github.event_name == 'schedule' }}
        uses: winpax/scoop-setup@v1.0.0
        with:
          admin: false
        continue-on-error: true
